create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  "memberCode" text not null unique,
  name text not null,
  phone text,
  birthday date,
  "pointsBalance" integer not null default 0,
  status text not null default 'active',
  "createdAt" bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  "updatedAt" bigint not null default ((extract(epoch from now()) * 1000)::bigint)
);

create table if not exists public.loyalty_transactions (
  id bigint generated by default as identity primary key,
  "customerId" bigint references public.customers(id) on delete set null,
  "customerName" text,
  "memberCode" text,
  "transactionId" bigint,
  "receiptNo" text,
  type text not null,
  points integer not null,
  amount numeric(12,2) not null default 0,
  "beforePoints" integer not null default 0,
  "afterPoints" integer not null default 0,
  details text,
  "staffId" bigint,
  "staffName" text,
  datetime bigint not null
);

alter table public.transactions
add column if not exists "customerId" bigint,
add column if not exists "customerName" text,
add column if not exists "memberCode" text,
add column if not exists "loyaltyEarned" integer not null default 0,
add column if not exists "loyaltyRedeemed" integer not null default 0,
add column if not exists "loyaltyDiscount" numeric(12,2) not null default 0;

create index if not exists idx_customers_member_code on public.customers ("memberCode");
create index if not exists idx_customers_name on public.customers (name);
create index if not exists idx_loyalty_customer_datetime on public.loyalty_transactions ("customerId", datetime desc);
create index if not exists idx_loyalty_receipt_no on public.loyalty_transactions ("receiptNo");

grant select, insert, update, delete on public.customers to anon, authenticated;
grant select, insert, update, delete on public.loyalty_transactions to anon, authenticated;
grant usage, select on sequence public.customers_id_seq to anon, authenticated;
grant usage, select on sequence public.loyalty_transactions_id_seq to anon, authenticated;

alter table public.customers enable row level security;
alter table public.loyalty_transactions enable row level security;

drop policy if exists "Allow app access to customers" on public.customers;
create policy "Allow app access to customers"
on public.customers
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Allow app access to loyalty transactions" on public.loyalty_transactions;
create policy "Allow app access to loyalty transactions"
on public.loyalty_transactions
for all
to anon, authenticated
using (true)
with check (true);
