create table if not exists public.membership_cards (
  id bigint generated by default as identity primary key,
  "cardCode" text not null unique,
  status text not null default 'available',
  "customerId" bigint references public.customers(id) on delete set null,
  "customerName" text,
  "batchName" text,
  "createdAt" bigint not null default ((extract(epoch from now()) * 1000)::bigint),
  "activatedAt" bigint,
  "disabledAt" bigint,
  notes text
);

alter table public.customers
add column if not exists "cardId" bigint,
add column if not exists "activatedAt" bigint;

create index if not exists idx_membership_cards_code on public.membership_cards ("cardCode");
create index if not exists idx_membership_cards_status on public.membership_cards (status);
create index if not exists idx_membership_cards_customer on public.membership_cards ("customerId");

grant select, insert, update, delete on public.membership_cards to anon, authenticated;
grant usage, select on sequence public.membership_cards_id_seq to anon, authenticated;

alter table public.membership_cards enable row level security;

drop policy if exists "Allow app access to membership cards" on public.membership_cards;
create policy "Allow app access to membership cards"
on public.membership_cards
for all
to anon, authenticated
using (true)
with check (true);
